[METADATA]
network = "main"
token_metadata = "https://clixprotocol.github.io/.well-known/token-meta.json"

[[CURRENCIES]]
code = "CLIX" 
issuer = "rNqqXuG7E774TcBoHiPKeoaRK9nBRSNnQu"
name = "CLIX"
desc = "Earn for engagement. The decentralized rewards token powering the future of clicks."
icon = "https://clixprotocol.github.io/.well-known/logo.png"
image = "https://clixprotocol.github.io/.well-known/logo.png"
url = "https://clixprotocol.github.io"
display_decimals = 2

[ACCOUNTS]
address = "rNqqXuG7E774TcBoHiPKeoaRK9nBRSNnQu"
