[METADATA]
network = "main"

[[CURRENCIES]]
code = "434C495800000000000000000000000000000000"  # Hex of "CLIX" with 24 zero padding
issuer = "rNqqXuG7E774TcBoHiPKeoaRK9nBRSNnQu"
name = "CLIX"
desc = "Earn for engagement. The decentralized rewards token powering the future of clicks."
icon = "https://clixprotocol.github.io/logo.png"
image = "https://clixprotocol.github.io/logo.png"
url = "https://clixprotocol.github.io"
display_decimals = 2

[[ACCOUNTS]]
address = "rNqqXuG7E774TcBoHiPKeoaRK9nBRSNnQu"
